import { useState } from "react"

const VERDICT_EMOJI = {
  TRUE: "✅", FALSE: "❌", PARTIALLY_TRUE: "⚠️",
  UNVERIFIABLE: "❓", CONFLICTING: "⚡", OPINION: "💬"
}

function generateReportText(report, inputText) {
  const lines = []

  lines.push("═══════════════════════════════════════")
  lines.push("  VERITASAI — FACT-CHECK REPORT")
  lines.push("═══════════════════════════════════════")
  lines.push("")
  lines.push(`📊 Credibility Score: ${report.credibility_score}/100`)
  lines.push(`📈 Overall Accuracy: ${report.overall_accuracy}%`)
  lines.push("")
  lines.push(`✅ True: ${report.true_count}  |  ❌ False: ${report.false_count}  |  ⚠️ Partial: ${report.partial_count}`)
  if (report.conflict_count > 0) lines.push(`⚡ Conflicting: ${report.conflict_count}`)
  if (report.unverifiable_count > 0) lines.push(`❓ Unverifiable: ${report.unverifiable_count}`)
  lines.push("")

  if (report.ai_text_probability != null) {
    lines.push(`🤖 AI Text Probability: ${Math.round(report.ai_text_probability * 100)}%`)
    lines.push("")
  }

  lines.push("───────────────────────────────────────")
  lines.push("  DETAILED CLAIM VERIFICATION")
  lines.push("───────────────────────────────────────")
  lines.push("")

  for (const claim of (report.claims || [])) {
    const emoji = VERDICT_EMOJI[claim.verdict] || "❓"
    lines.push(`${emoji} [${claim.verdict}] (${claim.confidence}% confidence)`)
    lines.push(`   "${claim.text}"`)
    if (claim.reasoning) {
      lines.push(`   Reasoning: ${claim.reasoning}`)
    }
    if (claim.evidence?.length > 0) {
      lines.push(`   Sources:`)
      for (const e of claim.evidence) {
        lines.push(`     • [Tier ${e.source_tier}] ${e.title}`)
        lines.push(`       ${e.url}`)
      }
    }
    lines.push("")
  }

  lines.push("───────────────────────────────────────")
  lines.push(`  Input: "${(inputText || "").slice(0, 100)}${(inputText || "").length > 100 ? "..." : ""}"`)
  lines.push(`  Generated by VeritasAI`)
  lines.push("═══════════════════════════════════════")

  return lines.join("\n")
}

export default function ExportReport({ report, inputText }) {
  const [copied, setCopied] = useState(false)
  const [format, setFormat] = useState("clipboard")

  const handleCopy = async () => {
    const text = generateReportText(report, inputText)
    try {
      await navigator.clipboard.writeText(text)
      setCopied(true)
      setTimeout(() => setCopied(false), 2500)
    } catch {
      // Fallback for older browsers
      const ta = document.createElement("textarea")
      ta.value = text
      document.body.appendChild(ta)
      ta.select()
      document.execCommand("copy")
      document.body.removeChild(ta)
      setCopied(true)
      setTimeout(() => setCopied(false), 2500)
    }
  }

  const handleDownload = () => {
    const text = generateReportText(report, inputText)
    const blob = new Blob([text], { type: "text/plain" })
    const url = URL.createObjectURL(blob)
    const a = document.createElement("a")
    a.href = url
    a.download = `veritasai-report-${Date.now()}.txt`
    a.click()
    URL.revokeObjectURL(url)
  }

  return (
    <div style={{
      display: "flex",
      gap: 10,
      marginTop: 24,
      paddingTop: 20,
      borderTop: "1px solid var(--border)",
      flexWrap: "wrap",
      alignItems: "center"
    }}>
      <span style={{
        fontSize: 13,
        fontWeight: 700,
        letterSpacing: 1,
        color: "var(--text-muted)",
        marginRight: 8
      }}>EXPORT</span>

      <button
        onClick={handleCopy}
        style={{
          padding: "10px 20px",
          background: copied ? "var(--green)" : "var(--navy)",
          color: "white",
          border: "none",
          fontSize: 13,
          fontWeight: 700,
          letterSpacing: 1,
          cursor: "pointer",
          fontFamily: "'DM Sans', sans-serif",
          transition: "background 0.2s"
        }}
      >{copied ? "✓ COPIED!" : "📋 COPY REPORT"}</button>

      <button
        onClick={handleDownload}
        style={{
          padding: "10px 20px",
          background: "transparent",
          color: "var(--text-dim)",
          border: "1px solid var(--border)",
          fontSize: 13,
          fontWeight: 600,
          letterSpacing: 1,
          cursor: "pointer",
          fontFamily: "'DM Sans', sans-serif",
          transition: "border-color 0.2s"
        }}
      >📥 DOWNLOAD .TXT</button>
    </div>
  )
}
